src/connect-proxy/device.ts, test/app.ts, test/connect-proxy/device.ts
=> api: Remove references to `is_web_accessible` device attr

package-lock.json, package.json
=> lint: Auto-prettify staged changes using husky/lint-staged

Dockerfile
=> Update open-balena-base to v5.0.1

config/confd/templates/env.tmpl, config/confd_env_backend/templates/env.tmpl, config/services/open-balena-vpn-api.service
=> vpn-api: set FORWARD chain policy on startup

bin/entry.sh, config/confd/templates/server.conf.tmpl, config/confd_env_backend/templates/server.conf.tmpl, package-lock.json, package.json, src/connect-proxy/app.ts, src/connect-proxy/worker.ts, src/vpn-api/utils/clients.ts, src/vpn-api/utils/netmask.ts, src/vpn-api/utils/request.ts, src/vpn-api/worker.ts, test/app.ts, typings/openvpn-client.d.ts
=> Maintenance Fixes/Updates

.github/CODEOWNERS
Connects-to: #33
Signed-off-by: Heds Simons <heds@balena.io>
---
---
=> codeowners: Update with	@Page- & @hedss

.versionbot/CHANGELOG.yml
=> versionbot: add structured CHANGELOG.yml

repo.yml
=> versionist: set repo type to docker

config/confd/templates/haproxy.cfg.tmpl, config/confd_env_backend/templates/haproxy.cfg.tmpl, src/vpn-api/utils/openvpn.ts, src/vpn-api/worker.ts, typings/telnet-client.d.ts
=> management console fixes/improvements

src/vpn-api/app.ts
=> metrics: reduce cardinality of session bitrate metrics

src/vpn-api/worker.ts
=> vpn: guard against writing bandwidth metrics for unknown clients

src/vpn-api/metrics.ts
=> metrics: increase granularity of bitrate buckets

package-lock.json, package.json, src/vpn-api/api.ts, src/vpn-api/utils/clients.ts, src/vpn-api/utils/index.ts, src/vpn-api/utils/request.ts
=> vpn: use pooled request workers for client authentication via api

.circleci/config.yml
=> circle: fix deploy to staging job

src/connect-proxy/worker.ts
=> Only try to forward to the correct vpn instance if lookup fails

src/connect-proxy/device.ts, test/app.ts, test/connect-proxy/device.ts
=> Use a prepared query for getDeviceByUUID

config/services/open-balena-connect-proxy.service, config/services/open-balena-vpn-api.service, config/services/openvpn@.service.d/restart.conf
Signed-off-by: Matthew McGinn <matthew@balena.io>
=> systemd: move StartLimitIntervalSec to proper section

src/vpn-api/metrics.ts
Signed-off-by: Matthew McGinn <matthew@balena.io>
=> metrics: fix up metrics naming

package-lock.json, package.json, src/connect-proxy/device.ts, src/connect-proxy/worker.ts, src/utils/errors.ts, src/vpn-api/api.ts, src/vpn-api/utils/clients.ts, src/vpn-api/utils/service.ts
=> replace deprecated raven package with @sentry/node

config/confd/templates/env.tmpl
=> config: fix typo in env template

src/vpn-api/utils/openvpn.ts, src/vpn-api/worker.ts
=> vpn-api: reduce default log verbosity

src/vpn-api/utils/openvpn.ts, src/vpn-api/worker.ts
=> performance & logging fixes

src/utils/index.ts
=> Combine the worker id into the service name

config/services/open-balena-vpn-api.service, src/connect-proxy/worker.ts
=> Reduce log length for proxying messages

config/confd/templates/haproxy.cfg.tmpl, config/confd_env_backend/templates/haproxy.cfg.tmpl
=> haproxy: remove proxy process metrics config

Dockerfile, config/confd/templates/haproxy.cfg.tmpl, config/confd_env_backend/templates/haproxy.cfg.tmpl, config/services/node-exporter.service, config/services/process-exporter.service
=> Add `node-exporter` & expose haproxy stats to prometheus

.circleci/config.yml
Signed-off-by: Michael Angelos Simos <michalis@balena.io>
---
=> CircleCI: Fix staging auto-deployments

config/confd/templates/haproxy.cfg.tmpl, config/confd_env_backend/templates/haproxy.cfg.tmpl
=> haproxy: disable checks on vpn workers

src/utils/clients.ts
=> Remove redundant code

.circleci/config.yml
Signed-off-by: Michael Angelos Simos <michalis@balena.io>
---
---
=> circleci: Rename deploy job

src/proxy-worker.ts, src/utils/device.ts, test/app.ts
=> proxy: refuse to forward tunnels via self and detect forwarding loops

openvpn/scripts/client-connect.sh, openvpn/scripts/client-disconnect.sh, src/api.ts, src/utils/clients.ts
=> logging: include worker_id in state update messages

src/api.ts
=> api: filter client state updates by worker id

src/api.ts
=> metrics: always decrement online count on client-disconnect event

src/api.ts
=> api: fix typo in logger call

src/utils/openvpn.ts
=> vpn: kill orphan server processes on startup

src/proxy-worker.ts
=> proxy: fix incorrect headers inserted into stream

src/utils/openvpn.ts, src/vpn-worker.ts
=> vpn-worker: convert promise chains to async/await

package-lock.json, package.json, src/proxy-worker.ts, src/utils/service.ts, test/app.ts
=> convert more promise chains to async/await

.dockerignore
=> Remove *.md from dockerignore so the changelog is included

.circleci/config.yml
=> circleci: optimise build and update config to v2.1 syntax

.circleci/config.yml
=> circleci: fix deploy to staging job

.circleci/config.yml
nth time is the charm…
---
---
---
=> circleci: fix/optimise deploy to staging job

src/app.ts, src/utils/config.ts, tsconfig.json
Signed-off-by: ab77 <anton@balena.io>
=> resolve service instance count from podinfo

config/confd_env_backend/templates/env.tmpl, package-lock.json, src/utils/config.ts
* move logic to getInstanceCount function
* refactor conf.d logic to handle additional cases
Signed-off-by: ab77 <anton@balena.io>
=> refactor instance number autodetect

Dockerfile
Connects-to: balena-io/balena-on-balena#191
---
---
=> dockerfile: explicitly disable os-provided openvpn services

config/confd/templates/env.tmpl, config/confd_env_backend/templates/env.tmpl
=> Increase UV_THREADPOOL_SIZE to 128

src/utils/index.ts, test/app.ts, test/connect-proxy/device.ts, test/service.ts
=> Update to use api v6

.github/CODEOWNERS
Signed-off-by: Matthew McGinn <matthew@balena.io>
See: <url> 
---
---
=> meta: remove legacy codeowners

src/api.ts, src/app.ts, src/utils/clients.ts, src/utils/device.ts, src/utils/haproxy.ts, test/app.ts, test/service.ts
=> Make more use of native promises and async/await

package.json
Also the linting on prepush works very poorly on windows due to
complaints around line endings even if the committed line endings are
fine
See: <url> 
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, …
=> Remove linting on prepush as it's already handled on commit

Dockerfile
=> Update process exporter to 0.7.5

Dockerfile
=> Update node exporter to 1.2.2

src/utils/service.ts
=> Fix losing the ip address to register when retrying on error

config/confd/templates/server.conf.tmpl
=> Enforce minimum TLS v1.2

config/confd/templates/server.conf.tmpl
=> Allow ciphers to be configured

src/utils/clients.ts, src/utils/service.ts
=> Use timers/promises instead of Bluebird.delay

config/confd/templates/haproxy.cfg.tmpl
This avoids issues where it's auto-calculated from max connections but
ends up too small in practice and causes problems with the soft limit
even though the hard limit is much higher
See: <url> 
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the …
=> Manually specify ulimit in haproxy.cfg

Dockerfile
=> Update haproxy to 2.5

config/confd/templates/haproxy.cfg.tmpl
=> Remove `http-use-htx` option, it's now the default and only option

config/services/haproxy.service.d/haproxy.conf
=> Avoid an issue with failing to mount namespaces

Dockerfile, config/confd/templates/env.tmpl
Update open-balena-base from 13.1.0 to 13.2.0
See: <url> 
---
---
=> Update open-balena-base to 13.2.0

openvpn/scripts/client-connect.sh, openvpn/scripts/client-disconnect.sh, src/utils/openvpn.ts
=> Avoid passing unused data from openvpn connect scripts to nodejs

openvpn/scripts/client-connect.sh, openvpn/scripts/client-disconnect.sh, src/api.ts, src/utils/clients.ts, src/utils/openvpn.ts, test/app.ts
Change-type: major
See: <url> 
---
---
=> Stop sending virtual_address on connect events

package-lock.json, package.json, src/api.ts, src/utils/clients.ts
=> Simplify logging of successful updates

src/utils/clients.ts, test/app.ts
Change-type: major
See: <url> 
---
---
=> Report connecting/disconnecting clients in batches

src/utils/clients.ts
=> Only try to report if there's at least one uuid changed

Dockerfile, bin/stop.sh, config/confd/templates/env.tmpl, config/confd/templates/haproxy.cfg.tmpl, config/services/avahi-daemon.service.d/avahi-daemon.conf, config/services/dbus.service.d/dbus.conf, config/services/haproxy.service.d/haproxy.conf, src/app.ts, src/utils/errors.ts, src/vpn-worker.ts
=> Additional debug output

.circleci/config.yml
=> CircleCI: Remove docker layer caching

src/utils/errors.ts
=> Use Sentry.withScope instead of Sentry.configureScope as it fits better

bin/start.sh, config/confd/templates/env.tmpl, package-lock.json, package.json
=> Use nodejs source map support rather than source-map-support module

config/confd/templates/env.tmpl, openvpn/scripts/auth.sh, openvpn/scripts/client-connect.sh, openvpn/scripts/client-disconnect.sh, src/app.ts, src/utils/config.ts, src/utils/openvpn.ts, test/app.ts
=> Simplify openvpn scripts

src/app.ts, src/proxy-worker.ts, src/utils/device.ts
=> Remove some unnecessary lodash usage

src/utils/haproxy.ts, src/utils/openvpn.ts
=> Use await in all relevant places for async stack traces

src/utils/config.ts
=> Limit the VPN_INSTANCE_SUBNET_BITMASK to at most a /16

src/api.ts
Some of these can be blocking so the faster we respond the faster
openvpn will continue processing other clients
See: <url> 
--- …
=> Minimize time spent responding to openvpn scripts

src/api.ts, src/utils/clients.ts, src/utils/request.ts
=> Standardize request timeout to 59s

bin/stop.sh, config/confd/templates/env.tmpl, src/vpn-worker.ts
* add debug logging during connection draining
=> Remove superfluous process signaling

openvpn/scripts/client-connect.sh, src/utils/openvpn.ts, src/vpn-worker.ts
=> Revert "Handle client connect events asynchronously"

src/vpn-worker.ts
* prevent restart loops during draining
* check drain process is already in progress
* attempt to drain on unhandled exceptions in worker(s) instead of dropping all clients immediately
=> Handle uncaughtException(s)

Dockerfile
=> Update to haproxy 2.6

src/utils/openvpn.ts
=> Minor optimizations to the management stream parsing

src/utils/openvpn.ts
=> Emitted events should be in lowercase

config/confd/templates/haproxy.cfg.tmpl
=> Reduce haproxy logging when verbose logging is disabled

openvpn/scripts/auth.sh, src/utils/openvpn.ts, src/vpn-worker.ts
=> Avoid passing unnecessary arguments to the auth script

Dockerfile, package.json
=> Fix Husky hooks not being installed on fresh repo clones

package-lock.json, package.json, src/app.ts, src/utils/clients.ts, src/utils/config.ts, src/utils/device.ts, src/utils/request.ts, test/app.ts, test/connect-proxy/device.ts
=> Use @balena/env-parsing for shared env var parsing behavior

src/vpn-worker.ts
This avoids situations where due to client disconnection delays we end
up with clients being disconnected at a slower cadence than expected
and meaning that there may still be significant numbers connected at
the point the SIGTERM timeout is reached
See: <url> 
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you …
=> Avoid delays in client disconnection from affecting the draining cadence

src/api.ts
=> Use a ref count rather than worker map for out of sync disconnects

config/confd/templates/haproxy.cfg.tmpl
Programatically configure HAProxy multi-threading.
=> HAProxy thread control

src/vpn-worker.ts
This helps avoid confusion as to whether it is triggered by server side or client side
See: <url> 
---
---
=> Use `connection draining` in relevant logs rather than `disconnecting`

.github/workflows/flowzone.yml
=> Use self-hosted runners to avoid failing cargo builds when emulated

.github/workflows/flowzone.yml
* https://github.com/product-os/flowzone/pull/629
* https://github.com/balena-io/open-balena-vpn/pull/337
change-type: patch
See: <url> 
---
---
=> test external contributions

.github/workflows/flowzone.yml
change-type: patch
See: <url> 
---
---
=> test internal contribution

Dockerfile
Update open-balena-base from 14.7.2 to 14.10.0
See: <url> 
---
---
=> Update open-balena-base to 14.10.0

src/api.ts
=> Stop reporting out of sync disconnects to sentry

config/confd/templates/server.conf.tmpl
=> Add support for configuring openssl providers

Dockerfile
=> Use renovate annotations to manage dockerfile version args

package.json, src/api.ts, src/app.ts, src/proxy-worker.ts, src/utils/clients.ts, src/utils/config.ts, src/utils/device.ts, src/utils/haproxy.ts, src/utils/index.ts, src/utils/metrics.ts, src/utils/netmask.ts, src/utils/openvpn.ts, src/utils/request.ts, src/vpn-worker.ts, test/app.ts, test/connect-proxy/device.ts, test/service.ts, tsconfig.json
=> Switch to using typescript's `Node16` module resolution

Dockerfile, package-lock.json, package.json
Update balena/open-balena-base from 17.0.20 to 18.0.0
See: <url> 
---
---
=> Update balena/open-balena-base to v18 with nodejs 22.2.0

package.json, src/app.ts, src/proxy-worker.ts, src/utils/config.ts, src/utils/haproxy.ts, src/utils/index.ts, src/utils/netmask.ts, src/utils/openvpn.ts, src/vpn-worker.ts, test/connect-proxy/device.ts
=> Fix lint warnings

package-lock.json, package.json, src/api.ts, src/utils/errors.ts
=> Update @sentry/node to v8

test/connect-proxy/device.ts, test/connect-proxy/index.ts, test/index.ts, test/service.ts, test/utils/index.ts, test/utils/netmask.ts
=> Tests: avoid the need for `require`

src/api.ts, src/app.ts, src/proxy-worker.ts, src/utils/clients.ts, src/utils/index.ts, src/utils/service.ts, src/vpn-worker.ts, test/app.ts, test/service.ts
=> Avoid circular dependencies in utils

package.json, src/api.ts, src/app.ts, src/proxy-worker.ts, src/utils/clients.ts, src/utils/device.ts, src/utils/errors.ts, src/utils/index.ts, src/utils/openvpn.ts, src/utils/service.ts, src/vpn-worker.ts, test/app.ts, test/connect-proxy/device.ts, test/connect-proxy/index.ts, test/index.ts, test/service.ts, test/utils/index.ts, test/utils/netmask.ts, tsconfig.json
=> Convert to ES modules

package-lock.json, package.json
=> Update @sentry/node to ^8.30.0

src/api.ts
=> Change request log format to more closely match the api

test/app.ts
=> Tests: make use of use async/await

src/api.ts
This is in favor of the external log system handling timestamps rather than duplicating
See: <url> 
---
---
=> Remove date from the request log

package-lock.json, package.json, src/api.ts, src/proxy-worker.ts, src/utils/errors.ts
=> Update to sentry 9.x

src/app.ts
This avoids them potentially stacking up and causing slow downs or other issues
See: <url> 
---
---
=> Ensure there is only one ever one concurrent cluster metrics fetch

.gitattributes
=> Explicitly use lf eol for `.tmpl` files to work properly on windows

package-lock.json, package.json, src/utils/device.ts, src/utils/index.ts, src/utils/service.ts
https://balena.fibery.io/Work/Project/Backend-use-improved-pinejs-client-typings-1801
See: <url> 
---
---
=> Use balena model info to improve the pinejs-client typings

Dockerfile, src/utils/haproxy.ts
Update balena/open-balena-base from 19.2.1 to 20.0.0
See: <url> 
---
---
=> Update balena/open-balena-base to v20.0.0

config/s6-overlay/s6-rc.d/haproxy/finish, config/s6-overlay/s6-rc.d/haproxy/run, config/s6-overlay/s6-rc.d/node-exporter/run, config/s6-overlay/s6-rc.d/open-balena-vpn/run, config/s6-overlay/s6-rc.d/openvpn-exporter/run, config/s6-overlay/s6-rc.d/process-exporter/run, config/s6-overlay/s6-rc.d/vpn-drain/finish, config/s6-overlay/s6-rc.d/vpn-drain/run, config/s6-overlay/s6-rc.d/vpn-drain/type
s6-overlay sends signals directly to the main process (like systemd's
KillMode=mixed), so HAProxy's master-worker mode (-W) can handle signal
propagation natively. The master process receives SIGTERM and gracefully
shuts down workers without requiring custom signal forwarding logic.
Replace custom signal handling in open-balena-vpn with a dependency-based
approach that leverages s6's native service ordering. The vpn-drain service
runs as a no-op dependency that executes HAProxy drain logic in its finish
script before open-balena-vpn shuts down.
- Add vpn-drain service that sleeps infinity but drains HAProxy in finish script
- Remove signal handlers from open-balena-vpn/run script
- Use exec to run start.sh directly as PID 1 in the service
- Ensure proper shutdown order: vpn-drain finish → …
=> Simplify from background process management to direct execution

src/utils/device.ts
See: https://balena.fibery.io/Security/Information_Security_and_Reliability_Incident/Elevated-Device-VPN-Tunnel-Errors-150
See: [#balena-io/balenaCloud > Elevated Device VPN Tunnel Errors @ 💬](https://balena.zulipchat.com/#narrow/channel/346007-balena-io.2FbalenaCloud/topic/Elevated.20Device.20VPN.20Tunnel.20Errors/near/542354282)
See: <url> 
---
- …
=> getDeviceVpnHost: Fix the is_connected_to_vpn raw filter
