balena-io/open-balena-vpn

Dockerfile
package-lock.json
package.json
src/connect-proxy/device.ts
src/connect-proxy/worker.ts
src/errors.ts
src/utils/index.ts
test/connect-proxy/device.ts

When a tunnel is requested for a device which is not directly connected,
the connect-proxy will lookup the appropriate instance in the api and
transparently establish the tunnel via that server.
Connects-to: #20
Capture fewer errors in sentry, tidy up logging and handling of
expected errors.
Connects-to: #22 
---
- …

connect-proxy: Routing and Error Handling improvements

---

src/connect-proxy/device.ts

Add an additional check to the actions allowed when tunnelling
ports through the connect-proxy. This means that if the key used
is sufficiently privileged then any port can be tunnelled to a
device.
Signed-off-by: Rich Bayliss <rich@balena.io>

perms: Add tunnel-any check when tunnelling ports

---

config/confd/templates/haproxy.cfg.tmpl
config/confd_env_backend/templates/haproxy.cfg.tmpl

This restores external ip logging and deals with the warnings at startup
```
[WARNING] 202/134917 (79) : parsing [/etc/haproxy/haproxy.cfg:47] : 'tcp-smart-connect' ignored because frontend 'tcp-443' has no backend capability.
[WARNING] 202/134917 (79) : parsing [/etc/haproxy/haproxy.cfg:49] : 'timeout connect' will be ignored because frontend 'tcp-443' has no backend capability
[WARNING] 202/134917 (79) : parsing [/etc/haproxy/haproxy.cfg:51] : 'timeout server' will be ignored because frontend 'tcp-443' has no backend capability
[WARNING] 202/134917 (79) : config : missing timeouts for frontend 'http-80'.
| While not properly invalid, you will certainly encounter various problems
| with such a configuration. To fix this, please ensure that all following
| timeouts are set to a non-zero …
```

haproxy: restore logs and fix timeout configs

---

src/vpn-api/utils/service.ts

The code in the captureException() method 'try's
to get an ID. If it fails, it 'finally' registers
the exception passed to it. Unfortunately, because
it doesn't 'catch', if the 'try' fails, then the
error from it bubbles up and the code calling
'captureException' does not finalise. This is
most prevalent should the API not currently be
running, as it won't register and the timed retry
to register will never get called.
This will also fix other calls made with it.
Signed-off-by: Heds Simons <heds@balena.io>
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, …

service: Ensure captureException does not throw

---

src/api.ts
src/utils/metrics.ts
src/vpn-worker.ts

Connects-to: https://github.com/balena-io/balena-monitor/pull/94
HQ: https://github.com/balena-io/balena/issues/1869
Signed-off-by: Matthew McGinn <matthew@balena.io>

device-metrics: create timeseries per-device with device_uuid tag

---

package-lock.json
package.json
src/vpn-worker.ts
typings/flatstr.d.ts

`data.common_name` is constructed from openvpn logs via substrings/slices in such a way that a reference to the original large string is kept around, that string can be anywhere from 1-20kb from the looks of it and when multiplied per each uuid that ever connects it can end up leaking significant memory. `flatstr` purports to handle flattening these strings in a performant method and should be updated as new methods are necessary/etc so makes sense as the first thing to try, but there are alternatives, eg `Buffer.from(s).toString()` should apparently work as well

Avoid unintentionally keeping large strings in memory

---

config/confd/templates/server.conf.tmpl

Add data-ciphers-fallback to allow older openvpn clients to connect

---

config/services/haproxy.service.d/haproxy.conf

HAProxy is running out of FDs in production:
```
Limit                     Soft Limit           Hard Limit           Units     
Max open files            37563                1048576              files     
Limit                     Soft Limit           Hard Limit           Units     
Max open files            37563                1048576              files  
```
The container sets hard limit 1048576, but systemd is defaulting to soft limit 37563.
HAProxy logs are currently full of events like:
```
Nov 13 17:28:45 open-balena-vpn-799b5b7d66-27nc9 haproxy[110]: Proxy tcp-443 reached process FD limit (maxsock=37563). Please check 'ulimit-n' and restart.
Nov 13 17:28:45 open-balena-vpn-799b5b7d66-27nc9 haproxy[110]: Proxy tcp-443 reached process FD limit (maxsock=37563). Please check …
```

Raise soft open files limit for HAProxy

---

src/api.ts
src/utils/clients.ts

We never send the worker id to the api so even if it changes there's
still nothing to report and so we can potentially avoid unnecessary
state reports
See: <url> 
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review …

Ignore the worker id when deciding if we have a state change to report

---

src/api.ts
src/utils/clients.ts

Since the connected/disconnected status is the only thing that is
important to the api then comparing just that allows us to simplify the
code and ensure we only update when truly necessary

Only compare the connected state when deciding if we need to report it

---

package-lock.json
package.json
src/utils/clients.ts

This will make it more likely for reports to be batched and increase
the batch size, reducing the number of requests necessary without
adding a significant delay for reporting, this will also help throttle
in the case of report failures
See: <url> 
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major …

Add a 1s delay between batch reports to increase the chance of batching

---

openvpn/scripts/client-connect.sh
openvpn/scripts/client-disconnect.sh

These curl commands should never fail as they're talking to the local
nodejs instance, but if for some reason they do it's better to reject
the client than pretend things are ok because they're really not
See: <url> 
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand …

Allow the client-connect/disconnect script to fail if necessary

---

config/confd/templates/haproxy.cfg.tmpl

This will create 1 listening socket per thread and avoids lock
contention for the threads, at the cost of increasing the CPU usage
per thread slightly
See: <url> 
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review …

Shard haproxy's VPN connection listener to the number of threads

---

Dockerfile
package.json

This avoids errors when trying to install with `npm ci --production`
where husky won't exist whilst also working on windows
See: <url> 
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make …

Switch to conditionally calling husky install

---

src/api.ts
src/utils/clients.ts
src/vpn-worker.ts

This solves an issue that could happen where the device reconnects in
rapid succession and connects to another VPN container and then back to
the current one without yet having been recognized as disconnected from
the current VPN container and as such we would not send a connect event
for the reconnection. This would result in the device appearing to be
offline for the API (because it disconnected from the other instance)
whilst actually still being connected, just to this instance
See: <url> 
---
- '*Request Changes*' if this …

Always send a connect event to the API if the connected worker changes

---

package-lock.json
package.json
src/app.ts

Notably this will cause pinejs-client to use a version with native async/await and hence allow for async stack traces

Set desired es-version for downstream modules that support it

---

src/api.ts
src/utils/openvpn.ts
src/vpn-worker.ts

This avoids the case where a uuid could be a valid int and be parsed as a false positive and cause issues. It also avoids the overhead of parsing ints when their parsed form may never be needed.

Stop automatic int parsing of openvpn events to avoid false positives

---

src/utils/openvpn.ts

This fixes issues if `socket.connect` tries to connect using ipv6 localhost rather than ipv4
See: <url> 
---
---

Explicitly/consistently use 127.0.0.1 as the openvpn management host

---

config/confd/templates/server.conf.tmpl

balenaOS devices drop privileges after starting OpenVPN so the SIGUSR1 is unable to recreate the socket.
Instead, have the server push the ping-exit directive as per the OpenVPN docs. This way balenaOS will stop and restart the service.
Signed-off-by: Kyle Harding <kyle@balena.io>
See: https://github.com/balena-os/meta-balena/issues/1779
---
- '*Comment*' if you don't feel you have enough information to decide either way …

Push ping-exit directive to clients rather than ping-restart

---

config/confd/templates/env.tmpl
src/utils/config.ts
src/vpn-worker.ts

This avoids unnecessarily waiting for the full duration of the grace period if there are only a few clients connected
See: <url> 
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a …

Add a configurable minimum client drain rate when terminating

---

openvpn/scripts/client-connect-disconnect.sh

* this script signals the API that a client has connected (or disconnected) and it is important to understand if any of these events are failing to reach open-balena-vpn API as they can lead to balena-api being unaware of client VPN state change
change-type: patch

capture stderr logs from client connect/disconnect script

---

src/utils/device.ts
test/app.ts

Avoid redundant `eq true` when checking `is_connected_to_vpn` boolean

---

src/utils/device.ts
test/app.ts

Makes the query a bit more explicit, scoping the is_connected_to_vpn under the alias
before:
```
...$filter=manages__device/any(d:(d/uuid%20eq%20%27<UUID>%27)%20and%20is_connected_to_vpn)
```
after:
```
...$filter=manages__device/any(d:(d/uuid%20eq%20%27<UUID>%27)%20and%20d/is_connected_to_vpn)
```
See: https://balena.fibery.io/Security/Information_Security_and_Reliability_Incident/Elevated-Device-VPN-Tunnel-Errors-150
See: <url> 
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes …

getDeviceVpnHost: Make the raw is_connected_to_vpn filter more explicit using the alias
